# Generated by Django 2.1 on 2018-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbs',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
